=== olac/olac.github.com/OLAC/OLAC_doc.dtd
<!-- edited with XML Spy v4.3 (http://www.xmlspy.com) by Gary Simons (SIL International) -->
<!--<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE OLAC_doc [

DTD for OLAC documents
Gary Simons, SIL International, 16 Feb 2001
Last modified: 3 Dec 2002
-->
<!ELEMENT OLAC_doc (header, body, todo?, references?)>
<!--Header information for the document-->
<!ELEMENT header (status, title, baseName, issued, previousIssued, abstract, editors, copyright, changes)>
<!--The status of the document. When the OLAC document process is fully defined,
this will use a closed list of values.-->
<!ELEMENT status EMPTY>
<!ATTLIST status
	code (draft | proposed | candidate | adopted | superseded | withdrawn) #REQUIRED
	type (standard | recommendation | experimental | informational | implementation) #REQUIRED
>
<!--Title of document-->
<!ELEMENT title (#PCDATA)>
<!--Base name of file (that is, without path or .html extension)-->
<!ELEMENT baseName (#PCDATA)>
<!ATTLIST baseName
	cv (Code | Refine) #IMPLIED
>
<!--Date document was issued (yyyy-mm-dd)-->
<!ELEMENT issued (#PCDATA)>
<!--Date issued for previous version-->
<!ELEMENT previousIssued (#PCDATA)>
<!--An abstract for the document-->
<!ELEMENT abstract (p)>
<!--Paragraph-->
<!ELEMENT p (#PCDATA | i | tt | url | cit | xref)*>
<!--Italic-->
<!ELEMENT i (#PCDATA)>
<!--Teletype (i.e. Fixed pitch font)-->
<!ELEMENT tt (#PCDATA)>
<!--The content is a URL. The stylesheet will format it as a link.-->
<!ELEMENT url (#PCDATA)>
<!--Citation (used as a link to a work in the list of references)
The element content is the abbrev of a ref in the references section.
The stylesheet will make it a link and add [ ] around it.-->
<!ELEMENT cit (#PCDATA)>
<!--Cross-reference to something else in the document.
The content of the xref is the content of a <heading> or of the <tag> of
an <element> or the <code> of a <term>. The stylesheet will format it is a link to the
cross-referenced item.-->
<!ELEMENT xref (#PCDATA)>
<!--The editors of the document-->
<!ELEMENT editors (#PCDATA | url | br)*>
<!--Explicit line break-->
<!ELEMENT br EMPTY>
<!ELEMENT copyright (#PCDATA)>
<!--A description of the changes since the version named in <previousVersion>.
(The reader can follow that link to see the description of the previous set of
changes, and so on.)-->
<!ELEMENT changes (p | ul | ol)*>
<!--Unordered (i.e. bulleted) list-->
<!ELEMENT ul (li*)>
<!--List item-->
<!ELEMENT li (p | ul | ol | dl | blockquote | eg)*>
<!ELEMENT ol (li*)>
<!ATTLIST ol
	start CDATA #IMPLIED
>
<!--Definition list-->
<!ELEMENT dl (dt, dd)+>
<!ATTLIST dl
	style (list | table) "list"
>
<!--Defined term-->
<!ELEMENT dt (#PCDATA)>
<!--Definition-->
<!ELEMENT dd (p | ul | ol | dl | blockquote | eg)*>
<!ELEMENT blockquote (p | ul | ol | dl | blockquote | eg)*>
<!--A coded example. The stylesheet will format it in fixed-pitch type with a block
indent on the left. Use <br> within for line breaks.-->
<!ELEMENT eg (#PCDATA | br)*>
<!--Body of document-->
<!ELEMENT body (section+)>
<!--A section of the document. -->
<!ELEMENT section (heading, (p | ul | ol | dl | blockquote | eg | extensions)*, (subsection+ | element+ | term+)?)>
<!ELEMENT subsection (subheading, (p | ul | ol | dl | blockquote | eg)*)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT subheading (#PCDATA)>
<!--The documentation for an element of the metadata set. This is used only
in the OLAC Metadata Set document.-->
<!ELEMENT element (tag, name, definition, comment, attributes?, examples?, todo?)>
<!--The XML tag used for this metadata element.-->
<!ELEMENT tag (#PCDATA)>
<!--The name of the metadata element or controlled vocabulary term-->
<!ELEMENT name (#PCDATA)>
<!--One-line definition of what the element is used for or what the
conttrolled vaculary term represents.-->
<!ELEMENT definition (#PCDATA)>
<!--Comments on how the element of term is meant to be used.-->
<!ELEMENT comment (p | ul | ol)*>
<!--Describesany attributes which the element may have-->
<!ELEMENT attributes (p+)>
<!--Examples of appropriate uses of the element or term-->
<!ELEMENT examples (p | eg)*>
<!--List of things remaining to do in order to complete the document, or
the definition of a particular element or term.-->
<!ELEMENT todo (p*)>
<!--The documentation for a term in a controlled vocabulary. This is used only
in a document that defines a controlled vocabulary. Note that this element is
recursive so that a controlled vocabulary can encode a taxonomic hierarchy.-->
<!ELEMENT term (code, name, definition, comment?, examples?, history?, todo?, term*)>
<!ATTLIST term
	status (proposed | active | retired) "proposed"
>
<!--The coded value for this term. This is the string used as the value of
the code attributed in a metadata element. If includes the full path if it
is at a lower level in a hierarchy.-->
<!ELEMENT code (#PCDATA)>
<!ELEMENT history (event+)>
<!ELEMENT event (date, remedy?, comment?)>
<!ATTLIST event
	type (proposed | changed | retired | created) #REQUIRED
>
<!ELEMENT date (#PCDATA)>
<!ELEMENT remedy (#PCDATA)>
<!--A set of XDC extensions. Information from the xdc-extension-defn referenced by the href is placed in the current document.-->
<!ELEMENT extensions (extension+)>
<!ELEMENT extension EMPTY>
<!ATTLIST extension
	name CDATA #REQUIRED
	ns   CDATA #REQUIRED
	href CDATA #REQUIRED
>
<!--List of work cited in the document-->
<!ELEMENT references (ref*)>
<!--Reference for a cited work. The abbrev attribute is the label used to make
citations in the text (as the content of <cit>).-->
<!ELEMENT ref (#PCDATA | i | url | br)*>
<!ATTLIST ref
	abbrev ID #REQUIRED
>
<!ENTITY nbsp "">

=== olac/olac.github.com/REC/olac-extensions-20021130.xml
<?xml version="1.0"?>
<?xml-stylesheet href="OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "OLAC_doc.dtd">
<OLAC_doc>
<header>
<status code="proposed" type="recommendation"/>
<title>Recommended metadata extensions</title>
<baseName>olac-extensions</baseName>
<issued>20021130</issued>
<previousIssued></previousIssued>
<abstract><p>This document lists all  the metadata extensions that are
recommended  by the Open Language Archives Community for  use in
describing language resources.
(The date issued for this document is the revision date for the text
in section 1 and the list of extensions included in section 2. The
information about a particular extension may be more recent than this
date; see the specific revision date given for each extension.)
</p></abstract>
<editors>Gary Simons, SIL International
        (<url>mailto:gary_simons@sil.org</url>)<br/>Steven Bird, University of
        Melbourne (<url>mailto:sb@csse.unimelb.edu.au</url>)</editors>
<copyright>2002 Gary Simons (SIL International) and Steven Bird (University of Melbourne)</copyright>
<changes></changes>
</header>
<body><section><heading>Introduction</heading>
<p>The OLAC metadata standard <cit>OLAC-MS</cit> follows the generic resource description standard known as "Qualified Dublin Core" <cit>DCQ</cit>. In order to meet the specific needs of the language resources community, the OLAC metadata standard incorporates an extension mechanism that makes it possible to describe language resources with greater precision. The mechanism uses the <tt>xsi:type</tt> attribute to override the basic definition of a Dublin Core metadata element with a definition that has a more precise semantics. For instance, the following subject description,</p><eg>&lt;dc:subject&gt;Dschang language&lt;/dc:subject&gt;</eg><p>can be formally identified as pertaining to language and as relating to the specific language associated with a standardized language identification code by employing an OLAC extension:</p><eg>&lt;dc:subject xsi:type="olac:language" code="x-sil-BAN"/&gt;</eg><p>Details on how the extension mechanism works may be found in the last two sections of <cit>OLAC-MS</cit>.</p><p>Any party may develop a metadata extension and use it in OLAC metadata records. When an extension is proven to work and is judged to have wide relevance across the language resources community, then it may be put forward to the community as a recommended best practice. If, after following the process described in <cit>OLAC-Process</cit>, the community reaches consensus that  the extension should indeed be used where applicable by all OLAC member archives, then the extension achieves the status of an OLAC Recommendation.</p><p>This document provides the complete list of all extensions that have been adopted as OLAC Recommendations. Each extension is described in terms of a title and the following five attributes:</p>
<dl style="list">
<dt>Name</dt><dd><p>The symbolic name that is used as the value of the <tt>xsi:type</tt> attribute to indicate that the extension is being used in a metadata element.</p></dd>
<dt>Date</dt><dd><p>The latest revision date of the extension or its controlled vocabulary.</p></dd><dt>Applies to</dt><dd><p>The Dublin Core elements with which the extension may be used.</p></dd>
<dt>Description</dt><dd><p>A summary description of what the extension is used for.</p></dd>
<dt>Documentation</dt><dd><p>A link to a complete document that defines and exemplifies the extension. If the extension involves a controlled vocabulary, the document should also enumerate and define the terms of the vocabulary.</p></dd></dl></section>
<section><heading>Recommended extensions</heading>
<p>The Open Language Archives Community recommends that all participating data providers use the following metadata extensions for describing  language resources whenever they are applicable: </p>
<extensions>

<extension name="discourse-type" ns="olac" href="http://www.language-archives.org/OLAC/1.0/olac-discourse-type.xsd"/>
<extension name="language" ns="olac" href="http://www.language-archives.org/OLAC/1.0/olac-language.xsd"/>
<extension name="linguistic-field" ns="olac" href="http://www.language-archives.org/OLAC/1.0/olac-linguistic-field.xsd"/>
<extension name="linguistic-type" ns="olac" href="http://www.language-archives.org/OLAC/1.0/olac-linguistic-type.xsd"/>
<extension name="role" ns="olac" href="http://www.language-archives.org/OLAC/1.0/olac-role.xsd"/>

</extensions><p></p></section>
</body>
<references><ref abbrev="DCQ">Dublin Core
      Qualifiers.<br/>&lt;<url>http://dublincore.org/documents/2000/07/11/dcmes-qualifiers/</url>&gt;</ref><ref abbrev="OLAC-MS">OLAC Metadata Standard.<br/>&lt;<url>http://www.language-archives.org/OLAC/metadata.html</url>&gt;</ref><ref abbrev="OLAC-Process">OLAC Process.<br/>&lt;<url>http://www.language-archives.org/OLAC/process.html</url>&gt;</ref></references></OLAC_doc>

=== olac/olac.github.com/REC/bpr-20080711.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../OLAC_doc.xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "../OLAC_doc.dtd">
<OLAC_doc>
   <header>
       <status code="adopted" type="recommendation"/>
      <!-- Promoted to Candidate on 2008-07-16 -->
      <!-- Promoted to Adopted on 2008-12-19 -->
      <title>Best Practice Recommendations for Language Resource Description</title>
      <baseName>bpr</baseName>
      <issued>20080711</issued>
       <!-- N.B. The HREF in the <recommendations> element needs to be
       updated to usage-new.xml to generate a version based on work in
       progress. -->
       <previousIssued>20080229</previousIssued>
      <abstract>
         <p>This document expresses the consensus of the Open Language Archives Community on best
            practice recommendations for language resource description using the OLAC metadata
            standard <cit>OLAC-Metadata</cit>.</p>
      </abstract>
      <editors>Gary Simons, SIL International and Graduate Institute of Applied Linguistics
            (<url>mailto:gary_simons@sil.org</url>) <br/>Steven Bird, University of Melbourne and
         University of Pennsylvania (<url>mailto:sb@ldc.upenn.edu</url>) <br/>Joan Spanne, SIL
         International (<url>mailto:joan_spanne@sil.org</url>)</editors>
      <copyright>2008 Gary Simons (SIL International and Graduate Institute of Applied Linguistics),
         Steven Bird (University of Melbourne and University of Pennsylvania), and Joan Spanne (SIL
         International)</copyright>
      <changes><p>Fixes problem in numbering and clarifies that using
          an encoding scheme means using a value from the scheme.</p> </changes>
   </header>
    <body>
        
        <section>
         <heading>Introduction</heading>
         <p>This document expresses the consensus of the Open Language Archives Community on best
            practices for describing language resources using the OLAC metadata standard
               <cit>OLAC-Metadata</cit>. The standard itself specifies the formal constraints on the
            syntax of valid descriptions, but does not set requirements on the content of the
            metadata elements (beyond general conformance to the definitions of the qualified Dublin
            Core metadata set <cit>DCMT</cit>). This document provides more detailed guidance about
            the content of specific metadata elements.</p>
         <p>This document does not provide a complete set of advice about what the metadata elements
            mean or about how they should be used. Such advice is supplied in an OLAC informational
            note <cit>OLAC-Usage</cit>. This document lists the specific metadata usage guidelines
            that have been agreed upon by the OLAC community as representing best practice. It is
            not a requirement of participation that OLAC data providers follow these
            recommendations. However, these recommendations are used as the standard for evaluating
            the quality of the metadata records supplied by an OLAC data provider. </p>
      </section>
      <section>
         <heading>Recommendations</heading>
         <p>The following are the OLAC recommendations on best practices for describing language
            resources. Follow the "more" link to see the fuller discussion of an element in
               <cit>OLAC-Usage</cit> including definition, usage notes, and examples.</p>
         <recommendations href="../NOTE/usage-20080711.xml"/>
      </section>


   </body>

   <references>

      <ref abbrev="DCMT">DCMI Metadata
            Terms.<br/>&lt;<url>http://dublincore.org/documents/dcmi-terms/</url>&gt;</ref>

      <ref abbrev="OLAC-Language">OLAC Language
         Extension.<br/>&lt;<url>http://www.language-archives.org/REC/language.html</url>&gt;</ref>
      
      <ref abbrev="OLAC-Metadata">OLAC
            Metadata.<br/>&lt;<url>http://www.language-archives.org/OLAC/metadata.html</url>&gt;</ref>

      <ref abbrev="OLAC-Usage">OLAC Metadata Usage
            Guidelines.<br/>&lt;<url>http://www.language-archives.org/NOTE/usage.html</url>&gt;</ref>

   </references>
</OLAC_doc>

=== olac/olac.github.com/REC/type-20021212.xml
<?xml version="1.0"?>
<?xml-stylesheet href="OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "OLAC_doc.dtd">
<OLAC_doc>
  <header>
    <status code="proposed" type="recommendation"/>
    <title>OLAC Linguistic Data Type Vocabulary</title>
    <baseName>type</baseName>
    <issued>20021212</issued>
    <previousIssued>20020628</previousIssued>
    <abstract><p>
              This document specifies the codes, or controlled vocabulary, for the Linguistic Data Type extension of the DCMI Type element. These codes describe the content of a resource from the standpoint of recognized structural types of linguistic information. 
    </p></abstract>
    <editors>
      Helen Aristar Dry (<url>mailto:hdry@linguistlist.org</url>),
      Heidi Johnson (<url>mailto:ailla@ailla.org</url>)
    </editors>
    <copyright>
      Helen Aristar Dry (Eastern Michigan University),
      Heidi Johnson (University of Texas at Austin)
    </copyright>
    <changes>
<p>Adds: Language Description, Primary Text</p>
<p>Deletes: Transcription section, Annotation section, Dataset, Text section (changed to Primary Text), Description (changed to Language Description), subtypes of Lexicon. </p>
    </changes>
  </header>

  <body>
    <section>
    <heading>Introduction</heading>
<p>
Like all elements in the OLAC metadata standard, the Type element is both optional and repeatable. Since it is optional, the Linguistic Type extension of the Type element should only be used if a resource contains a significant amount of primary data and represents one of the structural types described below.  Many linguistic papers and analyses thus will not be described using this element.  However, the element may be repeated if a resource represents more than one linguistic type. So, for example, a primary text accompanied by a lexicon of vocabulary items would be described as both a primary text and a lexicon. 

</p>

<p>
In many cases, adequate description of a linguistic resource will require that the Linguistic Type extension be used in conjunction with the Discourse Type extension of the Type element, or the Linguistic extension of the Subject element. For example, a narrative text might be described as both a primary text (OLAC Linguistic Type) and a narrative (OLAC Discourse Type).
</p>

<p>
Note that a dataset should be described using the DCMI Type vocabulary, e.g. Dataset, Collection.  See: <cit>DC-TYPE</cit>.
</p>
    </section>

<section>
<heading>Linguistic Data Type</heading>
<p>
Each term in the controlled vocabulary is described in one of the
following subsections. The heading gives the encoded value for the
term that is to be used as the value of the code attribute of the
"OLAC-Linguistic-Type" extension of the Type metadata element
<cit>OLAC-MS</cit>. Under the heading, the term is described in four
ways. <i>Name</i> gives a descriptive label for the term.
<i>Definition</i> is a one-line summary of what the term
means. <i>Comments</i> offers more details on what the term
represents. Examples may also be given to illustrate how the term is
meant to be applied.
</p>
<!-- A resource which is a dataset should be classified using the vocabulary for the DCMI Type element.
<term>
  <code>dataset</code>
  <name>Dataset</name>
  <definition>The resource is a structured set of data items.</definition>
  <comment><p>
     A dataset is a collection of items organized in a
     structured format for some specific research purpose.</p>
  </comment>
  <examples><p>
     Examples of datasets are: a set of sentences
     illustrating deictic terms; an inflectional affix
     paradigm; a list of utterance tokens in a uniform
     context (e.g. "Say [pat] now."); a chart giving a
     phonemic inventory classified by place/manner; an audio
     recording of minimal pairs.
  </p></examples>
</term>
-->
<term>
  <code>lexicon</code>
  <name>Lexicon</name>
  <definition>The resource includes a systematic listing of lexical items.</definition>
  <comment><p>
    Lexicon may be used to describe any resource which
    includes a systematic listing of lexical items. Each
    lexical item may, but need not,  be accompanied by a
    definition, a description of the referent (in the case
    of proper names), or an indication of the item's
    semantic relationship to other lexical items.
  </p></comment>
  <examples><p>
    Examples include word lists (including comparative word
    lists), thesauri,  wordnets, framenets, and
    dictionaries, including specialized dictionaries such
    as bilingual and multilingual dictionaries,
    dictionaries of terminology, and dictionaries of proper
    names. Non-word-based examples include phrasal lexicons
    and lexicons of intonational tunes.
  </p></examples>
</term>

<term>
  <code>primary_text</code>
  <name>Primary Text</name>
  <definition>Linguistic material which is itself the object of study, typically material in the subject language which is a performance of a speech event, or the written analog of such an event.  </definition>
  <comment><p>
    Primary Text is used to describe material in the subject language; it reflects a speech event, or is the written analog, and embodies linguistic features  which make it an object of analysis or research.  Typically, a primary text has temporal structure.  Most often in a primary text, the timecourse of some real or fictional linguistic event, e.g., a conversation, elicitation session, or imagined scene, is carried over into the archived artifact.</p>

    <p>Note:  Primary_text describes the content of the
    resource, not the physical format.  A primary text may
    be recorded in different physical media, e.g. as
    videotaped, audiotaped, or written text.  Physical
    format is described using the Format element.
  </p></comment>
  <examples><p>
    Examples of primary texts include transcribed interlinear texts, letters, (audiotaped) elicitation sessions, (videotaped) rituals or story-telling sessions, and any other recorded speech or writing which exemplifies language structure or use in such a way as to become an object of study.  When a corpus is a collection of primary texts, it should be described both as a primary text (OLAC Linguistic Type) and as a collection (DC Type).
  </p></examples>
</term>

<term>
  <code>language_description</code>
  <name>Language Description</name>
  <definition>The resource describes a language or some aspect(s) of a language via a systematic documentation of linguistic structures.</definition>
  <comment><p>
Not every resource commonly termed 'descriptive' should be described with this code; for example, a description of Zamenhof, the creator of Esperanto, would not be classified using this code. Instead, the code should be reserved for a resource that describes a language or some aspect of a language, typically in prose with interspersed examples. 
  </p>
  <p>
The similarly named code, Language Documentation (in the Linguistic Subject extension) refers to a field of study. This category, Language Description, refers to recognized structural   types of linguistic information, which are the products of the field of study, e.g., grammars and field notes.
   </p>
  </comment>
  <examples><p>
Examples of descriptions include a formal grammar, a sketch grammar, field notes, a phonological sketch. 
  </p></examples>
</term>
</section>
</body>

<references>
  <ref abbrev="DC-TYPE">Dublin Core Type Vocabulary.<br/>
    &lt;<url>http://dublincore.org/usage/terms/dcmitype/</url>&gt;</ref>

  <ref abbrev="OLAC-MS">OLAC Metadata Set.<br/>
    &lt;<url>http://www.language-archives.org/OLAC/olacms.html</url>&gt;</ref>
</references>
</OLAC_doc>

=== olac/olac.github.com/NOTE/marc.xml
<?xml version="1.0"?>
<?xml-stylesheet href="../OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "../OLAC_doc.dtd">
<OLAC_doc>
   <header>
      <status code="draft" type="implementation"/>
      <title>A MARC-to-OLAC Crosswalk</title>
      <baseName>marc</baseName>
      <issued>20090428</issued>
      <previousIssued/>
      <abstract>
         <p>Describes the installation, configuration, and operation
            of a crosswalk for converting a MARC record collection
            into a static repository that complies with the
            <cit>OLAC-Repositories</cit> standard.</p>
      </abstract>
      
      <editors>Christopher Hirt, SIL International and Graduate Institute of Applied Linguistics
         (<url>mailto:chris_hirt@sil.org</url>) <br/>Gary Simons, SIL International and Graduate Institute of Applied Linguistics
         (<url>mailto:gary_simons@sil.org</url>) <br/>Joan Spanne, SIL International
         (<url>mailto:joan_spanne@sil.org</url>)</editors>
      <copyright>2009 Christopher Hirt (SIL International and Graduate Institute of Applied Linguistics),
         Gary Simons (SIL International and Graduate Institute of Applied Linguistics), and Joan Spanne (SIL International)</copyright>
      <changes> </changes>
   </header>
   <body>
      <section>
         <heading>Introduction</heading>
         <p>This note describes a system for transforming the MARC21
            catalog for a library or archive into a static repository
            that holds an OLAC metadata record for each MARC record
            identified as describing a language resource. The
            MARC-to-OLAC crosswalk adds two tasks to a general
            MARC-to-DC crosswalk. First, we require a filtering step
            to determine whether a record describes a language
            resource. Second, if it does, we must extract the
            specialized metadata that facilitates language resource
            discovery. A fairly narrow subset of Library of Congress
            Subject Headings (LCSH) is used in cataloging language
            resources. The simple existence of the word “language” in
            subfield $a of an entry element is the main clue;
            institution-specific cata¬loging policies may also prove
            relevant. If it contains one or more of these clues, a
            record passes through the filter stage. Then a
            transformation stage applies specialized mappings for
            identifying languages and the type of a language resource.
            OLAC metadata uses ISO 639-2/3
            [http://www.sil.org/iso639-3/] as an encoding scheme for
            precise identification of languages We have thus mapped
            LCSH “language names” to their corresponding ISO 639
            identifiers for use with DC:Language and OLAC’s “language
            as subject” extension of DC:Subject. Specific LCSH terms
            are also mapped to OLAC’s linguistic resource type
            vocabulary applied as an extension to DC:Type. </p>
         <p>The crosswalk is implemented with a series of XSL
            transforma¬tions driven by a Python wrapper script. The
            Python script applies the transformations in batches and
            is thereby able to process gigabytes of MARC data with
            minimal memory requirements. The preliminary filtering
            step is configured by specifying tests on any MARC field
            or subfield with simple string comparison. We use a
            two-stage filtering process in which the first stage (the
            “select stage”) uses tests to select the maximal set of
            MARC records to be considered for inclusion in the OLAC
            repository, while the second stage (the “reject stage”)
            uses tests to reject records that are in fact not wanted.
            The resulting record set is then transformed from MARC XML
            to OLAC’s XML-based format by means of an XSL stylesheet
            that defines an &lt;xsl:template> for each MARC field.
            An optional stylesheet is called to apply overriding
            institution-specific mappings. The complete source code
            and data tables for the crosswalk (including the LCSH to
            ISO 639-3 mappings) are being shared on an open-source
            basis.</p>
      </section>
      <section>
         <heading>Installation</heading>
         <p></p>
      </section>
      <section>
         <heading>Configuring the language resource filter</heading>
         <p>
         </p>
      </section>
      <section>
         <heading>Configuring the OLAC archive description</heading>
         <p> </p>
      </section>
      <section>
         <heading>Configuring the MARC-to-OLAC mapping</heading>
         <p> </p>
      </section>
      <section>
         <heading>Running the crosswalk</heading>
         <p> </p>
      </section>
      

   </body>
   <references>
     
      <ref abbrev="HSS_2009">Building a MARC-to-OLAC Crosswalk: 
         Repurposing Library Catalog Data for the 
         Language Resources Community, by Christopher Hirt, Gary
         Simons, and Joan Spanne. <i>Proceedings of the Joint
            Conference on Digital Libraries, 15–19 June 2009, Austin, Texas, USA</i>
         <br/>
         &lt;<url>http://www.oxygenxml.com/download.html</url>&gt;</ref>
      
      <ref abbrev="OLAC-Repositories">OLAC Repositories.
         <br/>&lt;<url>http://www.language-archives.org/OLAC/repositories.html</url>&gt;</ref>
      
   </references>

</OLAC_doc>
