=== olac/olac.github.com/OLAC/OLAC_doc.dtd
<!-- edited with XML Spy v4.3 (http://www.xmlspy.com) by Gary Simons (SIL International) -->
<!--<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE OLAC_doc [

DTD for OLAC documents
Gary Simons, SIL International, 16 Feb 2001
Last modified: 3 Dec 2002
-->
<!ELEMENT OLAC_doc (header, body, todo?, references?)>
<!--Header information for the document-->
<!ELEMENT header (status, title, baseName, issued, previousIssued, abstract, editors, copyright, changes)>
<!--The status of the document. When the OLAC document process is fully defined,
this will use a closed list of values.-->
<!ELEMENT status EMPTY>
<!ATTLIST status
	code (draft | proposed | candidate | adopted | superseded | withdrawn) #REQUIRED
	type (standard | recommendation | experimental | informational | implementation) #REQUIRED
>
<!--Title of document-->
<!ELEMENT title (#PCDATA)>
<!--Base name of file (that is, without path or .html extension)-->
<!ELEMENT baseName (#PCDATA)>
<!ATTLIST baseName
	cv (Code | Refine) #IMPLIED
>
<!--Date document was issued (yyyy-mm-dd)-->
<!ELEMENT issued (#PCDATA)>
<!--Date issued for previous version-->
<!ELEMENT previousIssued (#PCDATA)>
<!--An abstract for the document-->
<!ELEMENT abstract (p)>
<!--Paragraph-->
<!ELEMENT p (#PCDATA | i | tt | url | cit | xref)*>
<!--Italic-->
<!ELEMENT i (#PCDATA)>
<!--Teletype (i.e. Fixed pitch font)-->
<!ELEMENT tt (#PCDATA)>
<!--The content is a URL. The stylesheet will format it as a link.-->
<!ELEMENT url (#PCDATA)>
<!--Citation (used as a link to a work in the list of references)
The element content is the abbrev of a ref in the references section.
The stylesheet will make it a link and add [ ] around it.-->
<!ELEMENT cit (#PCDATA)>
<!--Cross-reference to something else in the document.
The content of the xref is the content of a <heading> or of the <tag> of
an <element> or the <code> of a <term>. The stylesheet will format it is a link to the
cross-referenced item.-->
<!ELEMENT xref (#PCDATA)>
<!--The editors of the document-->
<!ELEMENT editors (#PCDATA | url | br)*>
<!--Explicit line break-->
<!ELEMENT br EMPTY>
<!ELEMENT copyright (#PCDATA)>
<!--A description of the changes since the version named in <previousVersion>.
(The reader can follow that link to see the description of the previous set of
changes, and so on.)-->
<!ELEMENT changes (p | ul | ol)*>
<!--Unordered (i.e. bulleted) list-->
<!ELEMENT ul (li*)>
<!--List item-->
<!ELEMENT li (p | ul | ol | dl | blockquote | eg)*>
<!ELEMENT ol (li*)>
<!ATTLIST ol
	start CDATA #IMPLIED
>
<!--Definition list-->
<!ELEMENT dl (dt, dd)+>
<!ATTLIST dl
	style (list | table) "list"
>
<!--Defined term-->
<!ELEMENT dt (#PCDATA)>
<!--Definition-->
<!ELEMENT dd (p | ul | ol | dl | blockquote | eg)*>
<!ELEMENT blockquote (p | ul | ol | dl | blockquote | eg)*>
<!--A coded example. The stylesheet will format it in fixed-pitch type with a block
indent on the left. Use <br> within for line breaks.-->
<!ELEMENT eg (#PCDATA | br)*>
<!--Body of document-->
<!ELEMENT body (section+)>
<!--A section of the document. -->
<!ELEMENT section (heading, (p | ul | ol | dl | blockquote | eg | extensions)*, (subsection+ | element+ | term+)?)>
<!ELEMENT subsection (subheading, (p | ul | ol | dl | blockquote | eg)*)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT subheading (#PCDATA)>
<!--The documentation for an element of the metadata set. This is used only
in the OLAC Metadata Set document.-->
<!ELEMENT element (tag, name, definition, comment, attributes?, examples?, todo?)>
<!--The XML tag used for this metadata element.-->
<!ELEMENT tag (#PCDATA)>
<!--The name of the metadata element or controlled vocabulary term-->
<!ELEMENT name (#PCDATA)>
<!--One-line definition of what the element is used for or what the
conttrolled vaculary term represents.-->
<!ELEMENT definition (#PCDATA)>
<!--Comments on how the element of term is meant to be used.-->
<!ELEMENT comment (p | ul | ol)*>
<!--Describesany attributes which the element may have-->
<!ELEMENT attributes (p+)>
<!--Examples of appropriate uses of the element or term-->
<!ELEMENT examples (p | eg)*>
<!--List of things remaining to do in order to complete the document, or
the definition of a particular element or term.-->
<!ELEMENT todo (p*)>
<!--The documentation for a term in a controlled vocabulary. This is used only
in a document that defines a controlled vocabulary. Note that this element is
recursive so that a controlled vocabulary can encode a taxonomic hierarchy.-->
<!ELEMENT term (code, name, definition, comment?, examples?, history?, todo?, term*)>
<!ATTLIST term
	status (proposed | active | retired) "proposed"
>
<!--The coded value for this term. This is the string used as the value of
the code attributed in a metadata element. If includes the full path if it
is at a lower level in a hierarchy.-->
<!ELEMENT code (#PCDATA)>
<!ELEMENT history (event+)>
<!ELEMENT event (date, remedy?, comment?)>
<!ATTLIST event
	type (proposed | changed | retired | created) #REQUIRED
>
<!ELEMENT date (#PCDATA)>
<!ELEMENT remedy (#PCDATA)>
<!--A set of XDC extensions. Information from the xdc-extension-defn referenced by the href is placed in the current document.-->
<!ELEMENT extensions (extension+)>
<!ELEMENT extension EMPTY>
<!ATTLIST extension
	name CDATA #REQUIRED
	ns   CDATA #REQUIRED
	href CDATA #REQUIRED
>
<!--List of work cited in the document-->
<!ELEMENT references (ref*)>
<!--Reference for a cited work. The abbrev attribute is the label used to make
citations in the text (as the content of <cit>).-->
<!ELEMENT ref (#PCDATA | i | url | br)*>
<!ATTLIST ref
	abbrev ID #REQUIRED
>
<!ENTITY nbsp "">

=== olac/olac.github.com/REC/access.xml
<?xml version="1.0"?>
<?xml-stylesheet href="OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "OLAC_doc.dtd">
<OLAC_doc>
  <header>
    <status code="draft" type="recommendation" endDate="20030618"/>
    <title>OLAC Access Vocabulary</title>
    <baseName>access</baseName>
    <issued>20021119</issued>
    <previousIssued></previousIssued>
    <abstract>
      <p>Access is an attribute of the Rights element.  It provides a broad classification of
      the ways in which a resource may be used.  Users may have to seek more detailed information
      about a given resource, if Access = restricted, or if they wish to use the resource in
      a non-standard fashion.  Users are always advised to review the specific policies of the
      data provider before making use any resource.
      If the Rights element is absent, no assumptions can be made about the status of these and 
      other rights with respect to the resource.</p>
    </abstract>
    <editors>
      Heidi Johnson (<url>mailto:ailla@ailla.org</url>)
    </editors>
    <copyright>
      Heidi Johnson (University of Texas at Austin)
    </copyright>
    <changes></changes>
  </header>
  
  <body>
    <section>
    <heading>Introduction</heading>
     <p>The information in the Rights element is intended as a guide for potential users of
      the resource. Since intellectual property rights laws and customs can be expected to vary widely across countries 
      and within sub-communities, data providers must make individual arrangements concerning 
      the rights that control access to and use of their resources. A controlled vocabulary can 
      only provide a coarse classification of the types of use to which a resource may be put.  
      Details of the rights and restrictions associated with the resource, such as a copyright
      notice or reference to the specific policies of a data provider, should be specified
      in the element content.</p>
    </section>
    
    <section>
    <heading>Access</heading>
    <p>Each term of the controlled vocabulary is described in one of the
    following subsections. The heading gives the encoded value for the term that is
    to be used as the value of the <i>Access</i> attribute of the <i>Rights</i>
    metadata element <cit>OLAC-MS</cit>. Under the heading, the term is described in four ways. 
    <i>Name</i> gives a descriptive label for the term.
    <i>Definition</i> is a one-line summary of what the term means. <i>Comments</i>
    offers more details on what the term represents, and may also include examples
    given to illustrate how the term is meant to be applied.</p>

    <term>
      <code>restricted</code>
      <name>Restricted</name>
      <definition>Access to the resource is restricted.</definition>
      <comment>
      <p>The specific nature of the restriction is not defined by means of a controlled
      vocabulary. Data providers should supply a brief description in the Rights element content.</p>
      </comment>
      <examples>
      <eg>
      &lt;rights xsi:type="olac:access" code="restricted">Permission from the depositor is required.&lt;/rights> 
      </eg>
      </examples>
    </term>
    <term>
      <code>standard</code>
      <name>Standard</name>
      <definition>Access to the resource is standard.</definition>
      <comment>
        <p>Standard access means that the resource can be used like any published work (book, article,
        music cd, etc.); that is, standard laws and policies governing the fair use of the work apply.
        Such policies generally prohibit wholesale incorporation of the resource into another work or 
        copying and distribution of the resource.  They generally allow quotation of small portions 
        of the resource, and summaries, critiques, or analyses, provided that the resource is properly
        cited.</p>
      </comment>
    </term>
    <term>
      <code>non-profit</code>
      <name>Non-profit</name>
      <definition>The resource can be used for any non-profit purpose.</definition>
      <comment>
        <p>This level is intended to allow broader use of the resource than standard access allows.
        For example, the resource could be copied and distributed free of charge, for academic
        purposes, or it could be used to create derivative works, such as transcriptions, for 
        non-profit purposes.</p>
      </comment>
    </term>
    <term>
      <code>commercial</code>
      <name>Commercial</name>
      <definition>The resource can be used for commercial purposes.</definition>
      <comment>
        <p>The resource can be freely used for any purpose without explicit permission from the
        creators or data providers, including copying and distribution for profit, incorporation
        into commercial products, and the creation of derivative works.</p>
      </comment>
    </term>
    </section>
  </body>
 
  <todo>
    <p>Identify a good expression of standard access that we can cite or link to. What we really
    need is a repository of such expressions from different countries and sub-disciplines.</p>
    <p>Provide a standard for citing resources in an accessible place.</p>
  </todo>
  
  <references>
    <ref abbrev="OLAC-MS">OLAC Metadata Set.<br/>
      &lt;<url>http://www.language-archives.org/OLAC/olacms.html</url>&gt;</ref>
  </references>
  
</OLAC_doc>

=== olac/olac.github.com/NOTE/process_implementation.xml
<?xml version="1.0"?>
<?xml-stylesheet href="OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "OLAC_doc.dtd">
<OLAC_doc> 
  <header> 
    <status code="draft" type="implementation"></status>
    <title>Implementing the OLAC
      Process</title><baseName>process_implementation</baseName> 
    <issued>20010506</issued><previousIssued></previousIssued> 
    <abstract> 
      <p>Describes how the OLAC process <cit>OLAC-Process</cit> is implemented
        at <tt>www.language-archives.org</tt>.</p> 
    </abstract> 
    <editors>Gary Simons, SIL International
      (<url>mailto:gary_simons@sil.org</url>)<br/>Steven Bird, Linguistic Data
      Consortium (<url>mailto:sb@ldc.upenn.edu</url>) </editors><copyright>2001 Gary
    Simons (SIL International) and Steven Bird (University of
    Pennsylvania)</copyright> 
    <changes> 
    </changes> 
  </header> 
  <body> 
    <section> 
      <heading>Site organization</heading> 
      <p>The gateway for the Open Language Archives Community is hosted at
        <url>http://www.language-archives.org/</url>. The following are the pages in
        the root folder of the site:</p> 
      <eg>/                    Home page
/organization.html   How OLAC is organized
/archives.html       Index of participating archives
/services.html       Index of participating services
</eg>
      <p>The following are root-level folders:</p>
      <eg>/OLAC/    Holds documents in the standards track
/REC/     Holds documents in the recommendations track
/NOTE/    Holds docuemnts in the notes track
/src/     Holds XML source files for documents in the above three tracks
/docs/    Holds documents that are not official OLAC documents
/wg/      Holds the home pages for the working groups</eg>
      <p>An index page in each of these folders (except <tt>src</tt>) offers
        visitors a complete list of what is available.</p>
    </section> 
    <section> 
      <heading>Use of mailing lists</heading> 
      <p>Mailing lists are used to implement much of the business of the
        community. The mailing lists are hosted at
        <tt>listserv.linguistlist.org.</tt></p>
      <p>Two lists are closed. Their subscriber lists are maintained by the
        OLAC Coordinators. In order to prevent subscription requests from the public at
        large, the lists are not made visible on the OLAC site nor on the mailing list
        archives page at Linguist List <cit>LL-Archives</cit>. The identity of the
        subscribers, however, is open and visible on the OLAC Organization page
        <cit>OLAC-Organization</cit>. The list archives can also be openly accessed via
        the form for accessing unlisted archives <cit>LL-Unlisted</cit>. The two closed
        lists are:</p><dl><dt>OLAC-Advisors</dt><dd> 
      <p>A mailing list that the OLAC Coordinators use for interacting with the
        OLAC Advisory Board, and which the board members may also use for interacting
        with each other.</p></dd><dt>OLAC-Archives</dt><dd> 
      <p>A mailing list that the OLAC Coordinators use for interacting with the
        Participating Archives and Services, and which the participants may also use
        for interacting with each other. There is only one subscriber per participating
        archive or service, and that is the person who is designated by the sponsoring
        institution to be the official contact person for OLAC business. At the
        discretion of the Coordinators, a contact person from selected Prospective
        Participants may also be subscribed.</p></dd></dl>
      <p>All other lists are open. They are listed on the OLAC site and at
        Linguist List <cit>LL-Archives</cit>. They are set up in such a way that
        interested parties may subscribe themselves to the lists. There are two
        "built-in" public lists:</p><dl><dt>OLAC-General</dt><dd> 
      <p>A mailing list that the OLAC Coordinators use to make Calls for
        Pariticipation, Calls for Review, and other public announcements to the full
        list of Participating Individuals. This list is set up as a moderated list so
        that the only traffic on it is annoucements from OLAC.
        </p></dd><dt>OLAC-Implementors</dt><dd> 
      <p>A mailing list for a working group consisting of all those who are
        implementing the OLAC standards or are interested in doing so. While a working
        group is, in general, constituted for the purpose of developing designated
        documents and may dissolve once its documents are completed, this working group
        is created as a perpetual group to support those who are implementing the
        standards. It may also develop documents, but its existence is not dependent on
        this. This list is unmoderated so that implementors may interact freely with
        each other.</p></dd></dl> 
      <p>For every other working group, there is an open and unmoderated
        mailing list with a name of the form: OLAC-<i>Groupname</i></p>
    </section> 
    <section> 
      <heading>Working group pages</heading> 
      <p>Every working group has a home page on the OLAC site. That page
        includes the following information in a format which is uniform across all
        working group pages:</p> 
      <ul> 
        <li> 
          <p>the name of the working group</p> 
        </li> 
        <li> 
          <p>a statement of purpose for the working group</p> 
        </li> 
        <li> 
          <p>the name and email address of the chair</p> 
        </li> 
        <li> 
          <p>links to the mailing list which offer the following functions:
            list group members, read mail archive, join group, resign from group</p> 
        </li> 
        <li> 
          <p>links to ballots that are currently open </p> 
        </li> 
        <li> 
          <p>links to results of ballots that have closed</p> 
        </li> 
        <li> 
          <p>a listing of the documents of the working group</p> 
        </li> 
      </ul> 
      <p>The document listing should include both documents that are in
        progress and those that are. Only the latest version of each document should be
        listed since each version of a document gives a link to its previous version
        (and so on). For each document the following information should be shown:</p> 
      <ul> 
        <li> 
          <p>the name of the document (as a link)</p> 
        </li> 
        <li> 
          <p>the type of the document</p> 
        </li> 
        <li> 
          <p>the status of the document</p> 
        </li> 
        <li> 
          <p>the latest date of issue</p> 
        </li> 
        <li> 
          <p>an optional comment describing the next major milestone and a
            target date</p> 
        </li> 
      </ul> 
    </section> 
  </body>
  <references>
    <ref abbrev="LL-Unlisted">Access unlisted
      archives.<br/>&lt;<url>http://listserv.linguistlist.org/cgi-bin/wa?LIST</url>&gt;</ref>
    <ref abbrev="LL-Archives">List archives at
      LISTSERV.LINGUISTLIST.ORG.<br/>&lt;<url>http://listserv.linguistlist.org/archives/</url>&gt;</ref>
    <ref abbrev="OLAC-Organization">OLAC
      Organization.<br/>&lt;<url>http://www.language-archives.org/organization.html</url>&gt;</ref>
    <ref abbrev="OLAC-Process">OLAC
      Process.<br/>&lt;<url>http://www.language-archives.org/OLAC/process.html</url>&gt;</ref>
  </references>
</OLAC_doc>

=== olac/olac.github.com/REC/role-20021119.xml
<?xml version="1.0"?>
<?xml-stylesheet href="OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "OLAC_doc.dtd">
<OLAC_doc>
  <header>
    <status code="draft" type="recommendation"/>
    <title>OLAC Role Vocabulary</title>
    <baseName>role</baseName>
    <issued>20021119</issued>
    <previousIssued></previousIssued>
    <abstract>
      <p>Role is an attribute of both the Creator and Contributor elements. This document 
      specifies the controlled vocabulary of the role attribute used by OLAC. The role 
      attribute specifies the functional role of the entity named in the Creator or Contributor 
      element in the creation of a given resource.</p>
    </abstract>
    <editors>
          Heidi Johnson (<url>mailto:ailla@ailla.org</url>)
        </editors>
    <copyright>
          Heidi Johnson (University of Texas at Austin)
        </copyright>
    <changes></changes>
  </header>
  <body>
    <section>
      <heading>Introduction</heading>
      <p>Key points: multiple choices are allowed for a single participant.</p>
    </section>
    <section>
      <heading>Role</heading>
      <p>Each term of the controlled vocabulary is described in one of the
    following subsections. The heading gives the encoded value for the term that is
    to be used as the value of the <i>code</i> attribute of the <i>Creator</i>
    or <i>Contributor</i> metadata element <cit>OLAC-MS</cit>. Under the heading, 
    the term is described in four ways. <i>Name</i> gives a descriptive label for the term.
    <i>Definition</i> is a one-line summary of what the term means. <i>Comments</i>
    offers more details on what the term represents, and may also include examples
    given to illustrate how the term is meant to be applied.</p>
      <term>
        <code>annotator</code>
        <name>Annotator</name>
        <definition>The participant produced an annotation of this or a related resource.</definition>
      </term>
      <term>
        <code>artist</code>
        <name>Artist</name>
        <definition>The participant contributed original graphic or visual materials to the resource.</definition>
      </term>
      <term>
        <code>author</code>
        <name>Author</name>
        <definition>The participant contributed original writings to the resource.</definition>
      </term>
      <term>
        <code>compiler</code>
        <name>Compiler</name>
        <definition>The participant is responsible for collecting the sub-parts of the 
        resource together.</definition>
        <comment>
          <p>Should this refer only to someone who creates a <i>single</i> resource with multiple
                    parts, such as a book of short stories, or can it be used to identify a person who
                    produces a corpus of resources, which are probably archived separately?</p>
        </comment>
        <examples><p>A compiler of a book of short stories or a CD with several songs on it; 
          a collector of a corpus of recordings in some language or on a given topic; 
          a person who assembles a suite of software tools.</p>
        </examples>
      </term>
      <term>
        <code>consultant</code>
        <name>Consultant</name>
        <definition>The participant contributes expertise to the creation of a work.</definition>
        <comment>
          <p>This term is commonly used by field linguists for the native speakers who work with
          them in describing and analyzing a language.  They contribute their expertise in their
          native language to the resource, although their speech, sign, or writing may not appear 
          directly in  the resource.</p>
        </comment>
      </term>
      <term>
        <code>depositor</code>
        <name>Depositor</name>
        <definition>The participant was responsible for depositing the resource in an archive.</definition>
      </term>
      <term>
        <code>developer</code>
        <name>Developer</name>
        <definition>The participant developed the methodology or tools that constitute the resource,
        or that were used to create the resource.</definition>
        <examples><p>A software programmer, designer, or analyst; a designer of a questionnaire
        or research task.</p>
        </examples>
      </term>
      <term>
        <code>editor</code>
        <name>Editor</name>
        <definition>The participant reviewed, corrected, and/or tested the resource.</definition>
        <comment>
          <p>This role includes anyone whose role was editorial in nature, such as proof-readers,
                    debuggers, testers, etc.  It may overlap the Compiler role in some cases.</p>
        </comment>
      </term>
      <term>
        <code>illustrator</code>
        <name>Illustrator</name>
        <definition>The participant contributed drawings or other illustrations to the resource.</definition>
      </term>
      <term>
        <code>interviewer</code>
        <name>Interviewer</name>
        <definition>The participant conducted an interview that forms part of the resource.</definition>
      </term>
      <term>
        <code>participant</code>
        <name>Participant</name>
        <definition>The participant was present during the creation of the resource, but did not
        contribute substantially to its content.</definition>
        <comment>
          <p>This role is intended for minor participants such as audience members, whose voices 
          may be heard on a recording saying things like "oh, really".  These interlocutors need not have been
                    physically present.  They could be participants in some form of long-distance
                    communication, such as lurkers in an online discussion.</p>
        </comment>
      </term>
      <term>
        <code>performer</code>
        <name>Performer</name>
        <definition>The participant performed some portion of a recorded, filmed, or transcribed resource.</definition>
        <comment>
          <p>Performers differ from Speakers in that a performance is generally a planned, learned,
          or traditional work, defined in advance in terms of content or style.  The performer
          delivers a rendition of this work, which may be performed by others at other times.
          The distinction between Performer and Speaker is subtle, being based on a subjective
          evaluation of the content of the resource.</p>
        </comment>
        <examples><p>A narrator of a traditional myth; a person performing a ceremony or 
          delivering an oration or a sermon; native speakers recreating a traditional genre of 
          speech, such as ritual greetings or insults; a singer or musician.
        </p></examples>
      </term>
      <term>
        <code>photographer</code>
        <name>Photographer</name>
        <definition>The participant took the photograph, or shot the film, that appears in or 
                constitutes the resource.</definition>
      </term>
      <term>
        <code>recorder</code>
        <name>Recorder</name>
        <definition>The participant operated the recording machinery used to create the resource.</definition>
      </term>
      <term>
        <code>researcher</code>
        <name>Researcher</name>
        <definition>The resource was created as part of the participant's research, or the research
        presents interim or final results from the participant's research.</definition>
      </term>
      <term>
        <code>respondent</code>
        <name>Respondent</name>
        <definition>The participant acted as a research subject or responded to a questionnaire, the
                results of which study form the basis of the resource.</definition>
      </term>
      <term>
        <code>speaker/signer</code>
        <name>Speaker/Signer</name>
        <definition>The participant was a principal speaker/signer in a resource that consists of a
                recording, a film, or a  transcription of a recorded resource.</definition>
        <comment>
          <p>Speakers/signers are those whose voices/gestures predominate in a recorded or filmed 
          resource. (This resource may be a transcription of that recording.) They differ from 
          Performers in that the speech/sign that is recorded in the resource was not necessarily 
          planned or learned in advance. Note that this distinction is based on the origin and
          content of the resource, and not on specific activities of the participant.</p>
        </comment>
        <examples>
          <p>Participants in a recorded conversation, elicitation session, or informal 
          narration would be termed Speaker/Signers.  Audience members who do not participate 
          beyond the occasional backchannel would be termed Participants.</p>
        </examples>
      </term>
      <term>
        <code>sponsor</code>
        <name>Sponsor</name>
        <definition>The participant contributed financial support to the creation of the resource.</definition>
      </term>
      <term>
        <code>transcriber</code>
        <name>Transcriber</name>
        <definition>The participant produced a transcription of this or a related resource.</definition>
      </term>
      <term>
        <code>translator</code>
        <name>Translator</name>
        <definition>The participant produced a translation of this or a related resource.</definition>
      </term>
    </section>
  </body>
  
  <todo>
    <p>
      Elicit roles from language researchers other than documentary linguists.
      </p>
    </todo>
    
  <references>
    <ref abbrev="OLAC-MS">OLAC Metadata Set.<br/>
      &lt;<url>http://www.language-archives.org/OLAC/olacms.html</url>&gt;</ref>
  </references>
</OLAC_doc>
