=== olac/olac.github.com/OLAC/OLAC_doc.dtd
<!-- edited with XML Spy v4.3 (http://www.xmlspy.com) by Gary Simons (SIL International) -->
<!--<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE OLAC_doc [

DTD for OLAC documents
Gary Simons, SIL International, 16 Feb 2001
Last modified: 3 Dec 2002
-->
<!ELEMENT OLAC_doc (header, body, todo?, references?)>
<!--Header information for the document-->
<!ELEMENT header (status, title, baseName, issued, previousIssued, abstract, editors, copyright, changes)>
<!--The status of the document. When the OLAC document process is fully defined,
this will use a closed list of values.-->
<!ELEMENT status EMPTY>
<!ATTLIST status
	code (draft | proposed | candidate | adopted | superseded | withdrawn) #REQUIRED
	type (standard | recommendation | experimental | informational | implementation) #REQUIRED
>
<!--Title of document-->
<!ELEMENT title (#PCDATA)>
<!--Base name of file (that is, without path or .html extension)-->
<!ELEMENT baseName (#PCDATA)>
<!ATTLIST baseName
	cv (Code | Refine) #IMPLIED
>
<!--Date document was issued (yyyy-mm-dd)-->
<!ELEMENT issued (#PCDATA)>
<!--Date issued for previous version-->
<!ELEMENT previousIssued (#PCDATA)>
<!--An abstract for the document-->
<!ELEMENT abstract (p)>
<!--Paragraph-->
<!ELEMENT p (#PCDATA | i | tt | url | cit | xref)*>
<!--Italic-->
<!ELEMENT i (#PCDATA)>
<!--Teletype (i.e. Fixed pitch font)-->
<!ELEMENT tt (#PCDATA)>
<!--The content is a URL. The stylesheet will format it as a link.-->
<!ELEMENT url (#PCDATA)>
<!--Citation (used as a link to a work in the list of references)
The element content is the abbrev of a ref in the references section.
The stylesheet will make it a link and add [ ] around it.-->
<!ELEMENT cit (#PCDATA)>
<!--Cross-reference to something else in the document.
The content of the xref is the content of a <heading> or of the <tag> of
an <element> or the <code> of a <term>. The stylesheet will format it is a link to the
cross-referenced item.-->
<!ELEMENT xref (#PCDATA)>
<!--The editors of the document-->
<!ELEMENT editors (#PCDATA | url | br)*>
<!--Explicit line break-->
<!ELEMENT br EMPTY>
<!ELEMENT copyright (#PCDATA)>
<!--A description of the changes since the version named in <previousVersion>.
(The reader can follow that link to see the description of the previous set of
changes, and so on.)-->
<!ELEMENT changes (p | ul | ol)*>
<!--Unordered (i.e. bulleted) list-->
<!ELEMENT ul (li*)>
<!--List item-->
<!ELEMENT li (p | ul | ol | dl | blockquote | eg)*>
<!ELEMENT ol (li*)>
<!ATTLIST ol
	start CDATA #IMPLIED
>
<!--Definition list-->
<!ELEMENT dl (dt, dd)+>
<!ATTLIST dl
	style (list | table) "list"
>
<!--Defined term-->
<!ELEMENT dt (#PCDATA)>
<!--Definition-->
<!ELEMENT dd (p | ul | ol | dl | blockquote | eg)*>
<!ELEMENT blockquote (p | ul | ol | dl | blockquote | eg)*>
<!--A coded example. The stylesheet will format it in fixed-pitch type with a block
indent on the left. Use <br> within for line breaks.-->
<!ELEMENT eg (#PCDATA | br)*>
<!--Body of document-->
<!ELEMENT body (section+)>
<!--A section of the document. -->
<!ELEMENT section (heading, (p | ul | ol | dl | blockquote | eg | extensions)*, (subsection+ | element+ | term+)?)>
<!ELEMENT subsection (subheading, (p | ul | ol | dl | blockquote | eg)*)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT subheading (#PCDATA)>
<!--The documentation for an element of the metadata set. This is used only
in the OLAC Metadata Set document.-->
<!ELEMENT element (tag, name, definition, comment, attributes?, examples?, todo?)>
<!--The XML tag used for this metadata element.-->
<!ELEMENT tag (#PCDATA)>
<!--The name of the metadata element or controlled vocabulary term-->
<!ELEMENT name (#PCDATA)>
<!--One-line definition of what the element is used for or what the
conttrolled vaculary term represents.-->
<!ELEMENT definition (#PCDATA)>
<!--Comments on how the element of term is meant to be used.-->
<!ELEMENT comment (p | ul | ol)*>
<!--Describesany attributes which the element may have-->
<!ELEMENT attributes (p+)>
<!--Examples of appropriate uses of the element or term-->
<!ELEMENT examples (p | eg)*>
<!--List of things remaining to do in order to complete the document, or
the definition of a particular element or term.-->
<!ELEMENT todo (p*)>
<!--The documentation for a term in a controlled vocabulary. This is used only
in a document that defines a controlled vocabulary. Note that this element is
recursive so that a controlled vocabulary can encode a taxonomic hierarchy.-->
<!ELEMENT term (code, name, definition, comment?, examples?, history?, todo?, term*)>
<!ATTLIST term
	status (proposed | active | retired) "proposed"
>
<!--The coded value for this term. This is the string used as the value of
the code attributed in a metadata element. If includes the full path if it
is at a lower level in a hierarchy.-->
<!ELEMENT code (#PCDATA)>
<!ELEMENT history (event+)>
<!ELEMENT event (date, remedy?, comment?)>
<!ATTLIST event
	type (proposed | changed | retired | created) #REQUIRED
>
<!ELEMENT date (#PCDATA)>
<!ELEMENT remedy (#PCDATA)>
<!--A set of XDC extensions. Information from the xdc-extension-defn referenced by the href is placed in the current document.-->
<!ELEMENT extensions (extension+)>
<!ELEMENT extension EMPTY>
<!ATTLIST extension
	name CDATA #REQUIRED
	ns   CDATA #REQUIRED
	href CDATA #REQUIRED
>
<!--List of work cited in the document-->
<!ELEMENT references (ref*)>
<!--Reference for a cited work. The abbrev attribute is the label used to make
citations in the text (as the content of <cit>).-->
<!ELEMENT ref (#PCDATA | i | url | br)*>
<!ATTLIST ref
	abbrev ID #REQUIRED
>
<!ENTITY nbsp "">

=== olac/olac.github.com/REC/discourse-20021217.xml
<?xml version="1.0"?>
<?xml-stylesheet href="OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "OLAC_doc.dtd">
<OLAC_doc>
   <header>
      <status code="proposed" type="recommendation"/>
      <title>OLAC Discourse Type Vocabulary</title>
      <baseName>discourse</baseName>
      <issued>20021217</issued>
      <previousIssued>20021121</previousIssued>
      <abstract>
         <p> This document specifies the codes, or controlled vocabulary, for the Discourse Type
            extension of the OLAC Type element. These codes describe the content of a resource as
            structured in such a way as to represent a particular type of discourse. </p>
      </abstract>
      <editors> Heidi Johnson (<url>mailto:ailla@ailla.org</url>), Helen Aristar Dry
            (<url>mailto:hdry@linguistlist.org</url>) </editors>
      <copyright> Heidi Johnson (University of Texas at Austin), Helen Aristar Dry (Eastern Michigan
         University) </copyright>
      <changes>
         <p>Changed 'dialogue' to 'conversation' and updated examples for 'Unintelligible speech'. </p>
      </changes>
   </header>

   <body>
      <section>
         <heading>Introduction</heading>
         <p> The Discourse Type extension of the Type element is used to describe the content of a
            resource as representing discourse of a particular structural type. It will typically be
            used when the resource is itself an object of study, as, for example, when the resource
            is a primary text. So it will usually occur in conjunction with the Linguistic Data Type
            extension. For example, a narrative text would be described as both a primary text (OLAC
            Linguistic Type) and a narrative (OLAC Discourse Type). </p>
      </section>

      <section>
         <heading>Discourse Type</heading>

         <p> Each term in the controlled vocabulary is described in one of the following
            subsections. The heading gives the encoded value for the term that is to be used as the
            value of the code attribute of the "OLAC-Discourse-Type" extension of the Type metadata
            element <cit>OLAC-MS</cit>. Under the heading, the term is described in four ways. Name
            gives a descriptive label for the term. Definition is a one-line summary of what the
            term means. Comments offers more details on what the term represents. Examples may also
            be given to illustrate how the term is meant to be applied. </p>

         <term>
            <code>conversation</code>
            <name>Conversation</name>
            <definition>An interactive discourse with two or more participants.</definition>
            <examples>
               <p> Examples of conversations include dialogue, interviews, correspondence,
                  consultations, greetings and leave-takings. </p>
            </examples>
         </term>

         <term>
            <code>drama</code>
            <name>Drama</name>
            <definition>A planned, creative, rendition of discourse involving two or more
               participants.</definition>
            <comment>
               <p>Usually a drama involves mimesis of events, either real or imagined. </p>
            </comment>
            <examples>
               <p>Examples of drama include plays, skits, and enacted scenes. </p>
            </examples>
         </term>

         <term>
            <code>formulaic</code>
            <name>Formulaic</name>
            <definition>The resource is a ritually or conventionally structured discourse.</definition>
            <examples>
               <p>Examples of formulaic discourse are prayers, curses, blessings, charms, curing
                  rituals, marriage vows, and oaths. </p>
            </examples>
         </term>

         <term>
            <code>ludic</code>
            <name>Ludic</name>
            <definition>Ludic discourse is language whose primary function is to be part of play, or
               a style of speech that involves a creative manipulation of the structures of the
               language. </definition>
            <examples>
               <p>Examples of ludic discourse are play languages, jokes, secret languages, and
                  speech disguises. </p>
            </examples>
         </term>

         <term>
            <code>oratory</code>
            <name>Oratory</name>
            <definition>The art of public speaking, or of speaking eloquently according to rules or
               conventions.</definition>
            <examples>
               <p>Examples of oratory include sermons, lectures, political speeches, and
                  invocations. </p>
            </examples>
         </term>
         <term>
            <code>poetry</code>
            <name>Poetry</name>
            <definition>An artistic discourse conforming to a metrical, rhythmic, or phonological
               pattern.</definition>
            <examples>
               <p> Types of poetry include haiku, odes, limericks, commemorative verse, and verse
                  chants or songs. The latter may also be described as Singing. </p>
            </examples>
         </term>
         <term>
            <code>narrative</code>
            <name>Narrative</name>
            <definition>A monologic discourse which represents temporally organized events.</definition>
            <examples>
               <p> Types of narratives include historical, traditional, and personal narratives,
                  myths, folktales, fables, and humorous stories. </p>
            </examples>
         </term>

         <term>
            <code>procedural</code>
            <name>Procedural</name>
            <definition>An explanation or description of a method, process, or situation having
               ordered steps. </definition>
            <examples>
               <p>Examples of procedural discourses include recipes, instructions, and plans. </p>
            </examples>
         </term>

         <term>
            <code>report</code>
            <name>Report</name>
            <definition>A factual account of some event or circumstance.</definition>
            <examples>
               <p>Examples of reports include news reports, essays, and commentaries. </p>
            </examples>
         </term>


         <term>
            <code>singing</code>
            <name>Singing</name>
            <definition>"Words or sounds [articulated] in succession with musical inflections or
               modulations of the voice" OED. </definition>
            <examples>
               <p>Examples of singing include chants, songs, and choruses. </p>
            </examples>
         </term>


         <term>
            <code>unintelligible_speech</code>
            <name>Unintelligible speech</name>
            <definition>The resource consists of utterances that are not intended to be
               interpretable as ordinary language.</definition>
            <examples>
               <p>Examples of unintelligible speech include sacred languages, glossolalia, and
                  singing syllables (fa-la-la). </p>
            </examples>
         </term>

      </section>
   </body>

   <references>
      <ref abbrev="OLAC-MS">OLAC Metadata Set.<br/>
            &lt;<url>http://www.language-archives.org/OLAC/olacms.html</url>&gt;</ref>
   </references>
</OLAC_doc>

=== olac/olac.github.com/REC/language-20010319.xml
<?xml version="1.0"?>
<?xml-stylesheet href="OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "OLAC_doc.dtd">
<OLAC_doc> 
  <header> 
    <status type="recommendation" code="draft"/>
    <title>OLAC Language Vocabulary</title> 
    <baseName>language</baseName>
    <issued>20010319</issued> 
    <previousIssued/>
    <abstract> 
      <p> This document specifies the controlled vocabulary of language
        identifiers used by OLAC. </p> 
    </abstract> 
    <editors>Gary Simons, SIL International
      (<url>mailto:gary_simons@sil.org</url>)<br/>
        Steven Bird, University of Pennsylvania
      (<url>mailto:sb@ldc.upenn.edu</url>)</editors> 
    <copyright>2001 Gary Simons (SIL International) and Steven Bird (University of
        Pennsylvania)</copyright>
    <changes/>
  </header> 
  <body> 
    <section> 
      <heading>Introduction</heading> 
      <p>Language identification is an important dimension of language resource
        classification. However, the character-string representation of language names
        is problematic for several reasons: </p> 
      <ul> 
        <li> 
          <p>Different languages (in different parts of the world) may have the
            same name.</p> 
        </li> 
        <li> 
          <p>The same language may have a different name in each country where
            it is spoken.</p> 
        </li> 
        <li> 
          <p>Within the same country, the preferred name for a language may
            change over time.</p> 
        </li> 
        <li> 
          <p>In the early history of discovering new languages (before names
            were standardized), different people referred to the same language by different
            names.</p> 
        </li> 
        <li> 
          <p>For languages having non-Roman orthographies, the language name
            may have several possible romanizations.</p> 
        </li> 
      </ul> 
      <p>The sum of these facts taken together suggests that a standard based
        on names will not work. Rather, what is needed is a standard based on unique
        identifiers that do not change, combined with accessible documentation that
        clarifies the particular speech variety denoted by each identifier. </p> 
      <p>The information technology community has a standard for language
        identification, namely, ISO 639 <cit>ISO-639</cit>. Part 1 of this standard
        lists two-letter codes for identifying about 140 of the world's major
        languages; part 2 of the standard lists three-letter codes for identifying
        about 400 languages. ISO 639 in turn forms the core of another standard, RFC
        3166 <cit>RFC-3166</cit> (formerly RFC 1766 <cit>RFC-1766</cit>), which is the
        standard used for language identification in the xml:lang attribute of XML and
        in the language element of the Dublin Core Metadata Initiative. RFC 3166
        provides a mechanism for users to register new language identification codes
        for languages not covered by ISO 639, but very few additional languages have
        been registered. </p> 
      <p>Unfortunately, the existing standard falls far short of meeting the
        needs of the language resources community since it fails to account for more
        than 90% of the world's languages, and it fails to adequately document what
        languages the codes refer to <cit>Simons-2000</cit>. However, SIL's Ethnologue
        <cit>Ethnologue</cit> provides a complete system of language identifiers which
        is openly available on the Web. OLAC will employ the RFC 3166 extension
        mechanism which permits Ethnologue codes to be incorporated. </p> 
    </section> 
    <section> 
      <heading>Ethnologue codes</heading> 
      <p>The SIL Ethnologue <cit>Ethnologue</cit> provides some 6,800
        three-letter codes, along with detailed information about language names,
        genetic affiliations and geographical locus, amongst other things. </p> 
      <p>There are at least three ways to determine the Ethnologue code for a
        given language: </p> 
      <ol> 
        <li> 
          <p>Use the form interface provided on the Ethnologue site
            <cit>Ethnologue</cit>,</p> 
        </li> 
        <li> 
          <p>Use the LDC's temporary Ethnologue query form, giving simpler
            output <cit>LDC-Ethnologue</cit>,</p> 
        </li> 
        <li> 
          <p>Download an ASCII table of language codes
            <cit>Language-Codes</cit>, and load them into a relational database using the schema provided
            in <cit>Simons-2000</cit>.</p> 
        </li> 
      </ol> 
      <p>A three-letter Ethnologue code <tt>AAA</tt> will be represented
        as<tt>x-sil-AAA</tt>.</p> 
    </section> 
    <section> 
      <heading>Other RFC 1766 codes</heading> 
      <p>Other RFC 1766 language codes, such as "en" (English) and "en-us" (US
        English) may be used, however the Ethnologue codes are identified as OLAC Best
        Practice. </p> 
    </section> 
    <section> 
      <heading>Languages for which codes are not assigned</heading> 
      <p>The SIL Ethnologue only covers living and recently extinct languages,
        and no language codes currently exist for ancient languages (e.g. Akkadian),
        for proto-languages (e.g. Proto-Bantu) or more recent precursors of current
        languages (e.g. Middle English). Until a coding system is devised, these
        languages should be identified by their conventional name(s). </p> 
    </section> 
    <section> 
      <heading>Mapping to unqualified Dublin Core</heading> 
      <p>An OLAC data provider should support a standardized method for
        representing OLAC metadata in unqualified Dublin Core. For language
        identifiers, the procedure is as follows: </p> 
      <ol> 
        <li> 
          <p>Drop the language refinement of the subject element and prepend
            "Language: " to the content.</p> 
        </li> 
        <li> 
          <p>If there is an identifier but no content, look up the language
            name using the controlled vocabulary server to get a human-readable string, and
            make that the content.</p> 
        </li> 
        <li> 
          <p>Drop the identifier attribute and append its value, parenthesized,
            to the content.</p> 
        </li> 
      </ol> 
    </section> 
  </body> 
  <todo> 
    <p>Create an official controlled vocabulary server for the Ethnologue. </p>
    
  </todo> 
  <references> 
    <ref abbrev="OLAC-MS">OLAC Metadata
      Set<br/>&lt;<url>http://www.language-archives.org/OLAC/olacms.html</url>&gt;</ref>
    
    <ref abbrev="RFC-1766">Tags for the Identification of
      Languages<br/>&lt;<url>http://www.ietf.org/rfc/rfc1766.txt</url>&gt;</ref> 
    <ref abbrev="RFC-3066">Tags for the Identification of Languages (replaces
      1766)<br/>&lt;<url>ftp://ftp.isi.edu/in-notes/rfc3066.txt</url>&gt;</ref> 
    <ref abbrev="ISO-639">Codes for the Representation of Names of
      Languages-Part 2: Alpha-3
      Code<br/>&lt;<url>http://lcweb.loc.gov/standards/iso639-2/langhome.html</url>&gt;</ref>
    
    <ref abbrev="ISO-3166">Codes for the representation of names of countries
      and their subdivisions--Part 1: Country
      codes<br/>&lt;<url>http://www.din.de/gremien/nas/nabd/iso3166ma/</url>&gt;</ref>
    
    <ref abbrev="Simons-2000">Language identification in metadata descriptions
      of language archive
      holdings<br/>&lt;<url>http://www.ldc.upenn.edu/exploration/expl2000/papers/simons/simons.htm</url>&gt;</ref>
    
    <ref abbrev="Ethnologue">Ethnologue: Languages of the
      World<br/>&lt;<url>http://www.sil.org/ethnologue/</url>&gt;</ref> 
    <ref abbrev="LDC-Ethnologue">LDC's Temporary Ethnologue Controlled
      Vocabulary
      Server<br/>&lt;<url>http://wave.ldc.upenn.edu/OLAC/ethnologue/form.php3</url>&gt;</ref>
    
    <ref abbrev="Language-Codes">Table of Ethnologue Language
      Codes<br/>&lt;<url>http://www.language-archives.org/data/languagecodes.tab</url>&gt;</ref>
    
    <ref abbrev="Country-Codes">Table of Ethnologue Country
      Codes<br/>&lt;<url>http://www.language-archives.org/data/countrycodes.tab</url>&gt;</ref>
    
  </references>
</OLAC_doc>

=== olac/olac.github.com/NOTE/third-party-extensions.xml
<?xml version="1.0"?>
<?xml-stylesheet href="OLAC_doc.xsl" type="text/xsl"?>
<!DOCTYPE OLAC_doc SYSTEM "OLAC_doc.dtd">
<OLAC_doc><header><status code="draft" type="informational"/>
<title>Third Party Extensions</title>
<baseName>third-party-extensions</baseName>
<issued>20021204</issued>
<previousIssued></previousIssued>
<abstract><p>This document lists third-party metadata extensions that are known
to be compatible with the OLAC Metadata standards.  They have not attained the status of OLAC Recommendations, but data providers are encouraged to try any that seem relevant to the nature of their collection.</p></abstract>
<editors>Gary Simons, SIL International
        (<url>mailto:gary_simons@sil.org</url>)<br/>Steven Bird, University of
        Melbourne (<url>mailto:sb@csse.unimelb.edu.au</url>)</editors>
<copyright>2002 Gary Simons (SIL International) and Steven Bird (University of Melbourne)</copyright>
<changes></changes>
</header>
<body>

<section>

<heading>Introduction</heading>

<p>The OLAC Metadata standard <cit>OLAC-Metadata</cit> follows the generic
resource description standard known as "Qualified Dublin Core"
<cit>DCQ</cit>, and supports a powerful extension mechanism described
in <cit>OLAC-Extensions</cit>.
Any party may develop their own metadata extension and use it in OLAC metadata
records.  This document lists the third-party extensions which are known to
work with OLAC Metadata. Each
extension is described in terms of a title and the following five
attributes:</p>

<dl style="list">
<dt>Name</dt><dd><p>The symbolic name that is used as the value of the <tt>xsi:type</tt> attribute to indicate that the extension is being used in a metadata element.</p></dd>
<dt>Date</dt><dd><p>The latest revision date of the extension or its controlled vocabulary.</p></dd><dt>Applies to</dt><dd><p>The Dublin Core elements with which the extension may be used.</p></dd>
<dt>Description</dt><dd><p>A summary description of what the extension is used for.</p></dd>
<dt>Documentation</dt><dd><p>A link to a complete document that defines and exemplifies the extension. If the extension involves a controlled vocabulary, the document should also enumerate and define the terms of the vocabulary.</p></dd></dl></section>

<section><heading>Third party extensions</heading>

<p>There are currently no third-party extensions.</p>

<!--
<p>The following extensions are known to be compatible with OLAC Metadata <cit>OLAC-Metadata</cit>:</p>
-->

</section>

<section><heading>Hypothetical third party extensions</heading>

<p>The following hypothetical third party extensions are provided as examples:</p>


<extensions>
<extension ns="as" name="language" href="http://www.language-archives.org/devel/third-party/as-formosan.xsd"/>
<extension ns="childes" name="participant" href="http://www.language-archives.org/devel/third-party/childes.xsd"/>
<extension ns="ltworld" name="hlt-field" href="http://www.language-archives.org/devel/third-party/ltworld-hlt-field.xsd"/>
<extension ns="example" name="role" href="http://www.language-archives.org/devel/third-party/example.xsd"/>
<extension ns="netdc" name="price" href="http://www.language-archives.org/devel/third-party/netdc.xsd"/>
<extension ns="netdc" name="distribution" href="http://www.language-archives.org/devel/third-party/netdc.xsd"/>
<extension ns="netdc" name="memberyear" href="http://www.language-archives.org/devel/third-party/netdc.xsd"/>
<extension ns="netdc" name="license" href="http://www.language-archives.org/devel/third-party/netdc.xsd"/>
<extension ns="netdc" name="speechformat" href="http://www.language-archives.org/devel/third-party/netdc.xsd"/>
<extension ns="software" name="cpu" href="http://www.language-archives.org/devel/third-party/software-cpu.xsd"/>
<extension ns="software" name="os" href="http://www.language-archives.org/devel/third-party/software-os.xsd"/>
<extension ns="software" name="sourcecode" href="http://www.language-archives.org/devel/third-party/software-sourcecode.xsd"/>
</extensions>

</section>

</body>
<references>
<ref abbrev="DCQ">Dublin Core Qualifiers.<br/>&lt;<url>http://dublincore.org/documents/2000/07/11/dcmes-qualifiers/</url>&gt;</ref>
<ref abbrev="OLAC-Extensions">Recommended metadata extensions<br/>&lt;<url>http://www.language-archives.org/drafts/olac-extensions.html</url>&gt;</ref>
<ref abbrev="OLAC-Metadata">OLAC Metadata.<br/>&lt;<url>http://www.language-archives.org/OLAC/metadata.html</url>&gt;</ref>
</references></OLAC_doc>
