=== olac/olac.github.com/OLAC/0.4/olac.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:olac="http://www.language-archives.org/OLAC/0.4/"
        targetNamespace="http://www.language-archives.org/OLAC/0.4/"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified">

  <annotation>
    <documentation>
      Schema for the OLAC Metadata Set, Version 0.4
      Steven Bird, 2001-10-15
      Schema validated at http://www.w3.org/2001/03/webdata/xsv
      XSV 1.204/1.109 of 2001/10/03 21:06:42

      OLAC Metadata Set semantics available at:
      http://www.language-archives.org/OLAC/olacms-20011020.html
      Dublin Core semantics available at:
      http://dublincore.org/documents/1999/07/02/dces/

      Naming scheme:
      XXX:              the name of the vocabulary
      (YYY.)XXX:        the name of the element
      OLAC-XXX.xsd:     the XML Schema defining an OLAC vocabulary
      OLAC-XXX-Element: type of the XML element (inherits OLAC-Element)
      OLAC-XXX-Refine:  type of a CV for a refine attribute
      OLAC-XXX-Code:    type of a CV for a code attribute

      Changes since first release of 0.4:
      1. Modified regular expression for OAI identifiers to be in line with
         http://www.openarchives.org/OAI/1.1/oai-identifier.xsd   2002-03-01

      Changes since 0.3:
      1. Capitalization rules follow Dublin Core
         (a) metadata element names are no longer capitalized
         (b) vocabularies OLAC-Role, OLAC-Date, OLAC-Relation
             are no longer capitalized
         NB. other vocabularies with initial capitals are unchanged:
         * DC-Type (following Dublin Core)
         * OLAC-OS-Code (use of capitals seems right,
           e.g. Unix/SunOS, OS2)
         * OLAC-Sourcecode-Code (language names are conventionally
           capitalized, e.g. Lisp)

      2. A new optional "scheme" attribute has been added on all elements,
         to support external control of element content (e.g. for controlled
         vocabularies over dialect names; see http://arXiv.org/abs/cs/0110014)

      3. OLAC-Data has been renamed to OLAC-Linguistic-Type, in response
         to the UCSB workshop.

      4. The included schemas now have absolute pathnames (for xerces).

      5. The lang attribute of the olac element has been changed to langs,
         since the element content of a record could be in multiple languages.

      6. The title element now has an optional refine attribute which may
         take a single value "alternative" (following DCQ).

    </documentation>
  </annotation>

<!-- include schemas for the controlled vocabularies -->

  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-CPU.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Linguistic-Type.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Date.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Encoding.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Format.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Functionality.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Language.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-OS.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Relation.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Rights.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Role.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/OLAC-Sourcecode.xsd"/>
  <include schemaLocation="http://www.language-archives.org/OLAC/0.4/DC-Type.xsd"/>

<!-- the top-level element and its associated type -->

  <element name="olac" type="olac:OLACMS"/>

  <complexType name="OLACMS">
    <complexContent>
      <restriction base="anyType">
        <choice minOccurs="0" maxOccurs="unbounded">
          <element name="contributor" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Creator-Element"/>  <!-- same as creator -->
          <element name="coverage" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Element"/>
          <element name="creator" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Creator-Element"/>
          <element name="date" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Date-Element"/>
          <element name="description" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Element"/>
          <element name="format" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Format-Element"/>
          <element name="format.cpu" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-CPU-Element"/>
          <element name="format.encoding" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Encoding-Element"/>
          <element name="format.markup" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Element"/>
          <element name="format.os" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-OS-Element"/>
          <element name="format.sourcecode" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Sourcecode-Element"/>
          <element name="identifier" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Element"/>
          <element name="language" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Language-Element"/>
          <element name="publisher" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Element"/>
          <element name="relation" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Relation-Element"/>
          <element name="rights" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Rights-Element"/>
          <element name="source" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Element"/>
          <element name="subject" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Element"/>
          <element name="subject.language" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Language-Element"/>
          <element name="title" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Title-Element"/>
          <element name="type" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Type-Element"/>
          <element name="type.linguistic" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Linguistic-Type-Element"/>
          <element name="type.functionality" minOccurs="0" maxOccurs="unbounded"
            type="olac:OLAC-Functionality-Element"/>
        </choice>
        <attribute name="langs" type="NMTOKENS" default="en"/>
      </restriction>
    </complexContent>
  </complexType>

  <!-- OLAC-Element: the base type for all elements, enforcing string
    content and permitting a lang attribute defaulting to English.
    NB the English code is RFC 1766 in line with OLACMS document.
    new scheme attribute added for 0.4 -->

  <complexType name="OLAC-Element">
    <simpleContent>
      <extension base="string">
        <attribute name="lang" type="string" default="en"/>
        <attribute name="scheme" type="string"/>
      </extension>
    </simpleContent>
  </complexType>

  <!-- Version of OLAC-Element where the content is an OAI reference -->

  <simpleType name="OAI-Ref">
    <restriction base="string">
      <pattern value="oai:[a-zA-Z0-9]+:.*"/>  <!-- OAI identifier -->
    </restriction>
  </simpleType>

  <complexType name="OLAC-RefElement">
    <simpleContent>
      <extension base="olac:OAI-Ref">
        <attribute name="lang" type="string" default="en"/>
      </extension>
    </simpleContent>
  </complexType>

  <!-- Extensions of OLAC-Element for the individual elements -->

  <complexType name="OLAC-CPU-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-CPU-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Creator-Element">  <!-- shared by contributor -->
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="refine" type="olac:OLAC-Role-Refine"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Linguistic-Type-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-Linguistic-Type-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Date-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="refine" type="olac:OLAC-Date-Refine"/>
        <attribute name="code" type="olac:OLAC-Date-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Format-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-Format-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Encoding-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-Encoding-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Functionality-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-Functionality-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-OS-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-OS-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Language-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-Language-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Relation-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="refine" type="olac:OLAC-Relation-Refine"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Rights-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-Rights-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Sourcecode-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:OLAC-Sourcecode-Code"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Title-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="refine" type="string" fixed="alternative"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="OLAC-Type-Element">
    <simpleContent>
      <extension base="olac:OLAC-Element">
        <attribute name="code" type="olac:DC-Type-Code"/>
      </extension>
    </simpleContent>
  </complexType>

</schema>

=== olac/olac.github.com/OLAC/1.0/olac.xml
<?xml version="1.0" encoding="UTF-8"?>
<olac:olac xmlns:olac="http://www.language-archives.org/OLAC/1.0/"
           xmlns="http://purl.org/dc/elements/1.1/"
           xmlns:dcterms="http://purl.org/dc/terms/"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.language-archives.org/OLAC/1.0/
                http://www.language-archives.org/OLAC/1.0/olac.xsd">

  <title>A grammar of Kayardild. With comparative notes on Tangkic.</title>
  <creator>Evans, Nicholas D.</creator>
  <subject>Kayardild grammar</subject>
  <subject xsi:type="olac:language" olac:code="x-sil-GYD">Kayardild</subject>
  <subject xsi:type="olac:language" olac:code="en">English</subject>
  <description>Kayardild Grammar (ISBN 3110127954)</description>
  <publisher>Berlin - Mouton de Gruyter</publisher>
  <contributor xsi:type="olac:role" olac:code="author">Nicholas Evans</contributor>
  <format>hardcover, 837 pages</format>
  <relation>related to ISBN 0646119966</relation>
  <coverage>Australia</coverage>
</olac:olac>

=== olac/olac.github.com/tools/metadata/.xml
<?xml version="1.0" encoding="UTF-8"?>
<olac:olac
      xsi:schemaLocation="http://www.language-archives.org/OLAC/1.0/ http://www.language-archives.org/OLAC/1.0/olac.xsd" xmlns:olac="http://www.language-archives.org/OLAC/1.0/"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:dcterms="http://purl.org/dc/terms/"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>Language: An introduction to the study of speech</dc:title>
  <dcterms:created>1921</dcterms:created>
  <dcterms:issued>2000</dcterms:iss>
  <dc:creator xsi:type="olac:role" olac:code="author">Sapir, Edward</dc:creator>
  <dc:description>The noted linguist and anthropologist Edward Sapir
wrote this work to show language in relation to other fundamental 
interests--the problem of thought, the nature of the historical 
process, race, culture, art. This book is not only a study of language 
and culture, but ultimately on the world of relations and influence.
</dc:description>
  <dc:language xsi:type="olac:language" olac:code="en"/>
  <dc:subject xsi:type="olac:linguistic-field" olac:code="general_linguistics"/>
  <dc:type xsi:type="dcterms:DCMIType">Text</dc:type>
  <dc:publisher>New York: Bartleby.com</dc:publisher>
  <dc:identifier xsi:type="dcterms:URI">http://www.bartleby.com/186/</dc:identifier>
</olac:olac>

=== olac/olac.github.com/OLAC/0.4/olac.xml
<?xml version="1.0" encoding="UTF-8"?>
<olac
  xmlns="http://www.language-archives.org/OLAC/0.4/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.language-archives.org/OLAC/0.4/
                http://www.language-archives.org/OLAC/0.4/olac.xsd"
  langs="en x-sil-LLU">
  <contributor>Smith, John L.</contributor>
  <contributor refine="sponsor">National Science
    Foundation</contributor>
  <contributor>Smith, John L. (format conversion)</contributor>
  <subject.language code="en"/>
  <coverage>India</coverage>
  <coverage scheme="TGN">Guadalcanal (island)</coverage>
  <coverage>19th century</coverage>
  <creator>Bloomfield, Leonard</creator>
  <creator>Linguistic Society of America</creator>
  <creator refine="editor">Sapir, Edward</creator>
  <date code="1992"/>
  <date refine="modified" code="1996-10-16"/>
  <date code="1950">circa 1950</date>
  <description>The CALLHOME Japanese corpus of telephone speech consists
    of 120 unscripted telephone conversations between native speakers
    of Japanese. All calls, which lasted up to 30 minutes, originated
    in North America and were placed to locations overseas (typically
    Japan). Most participants called family members or close friends.
    This corpus contains speech data files ONLY, along with the
    minimal amount of documentation needed to describe the contents
    and format of the speech files and the software packages needed to
    uncompress the speech data. </description>
  <description>http://www.ldc.upenn.edu/Catalog/LDC96S37.html
  </description>
  <format code="text/xml">5,237 entries in a 1.2M XML
    file.</format>
  <format code="audio/wav">Duration: 153 seconds. Size: 3.3M.
    Sampling: 1 channel, 22 KHz, 8 bits.</format>
  <format.cpu code="ppc"/>
  <format.cpu code="x86">At least 64M memory</format.cpu>
  <format.os code="OS2"/>
  <format.os code="MSWindows">NT 4.0 or higher</format.os>
  <format.sourcecode code="C"/>
  <format.sourcecode code="Java">Version 1.2 library</format.sourcecode>
  <identifier>http://arxiv.org/abs/cs.CL/0010033</identifier>
  <identifier>Shelf 12, Box 7</identifier>
  <language code="en"/>
  <subject.language code="x-sil-SKY"/>
  <language code="fr"/>
  <subject.language code="x-sil-BAN">Dschang</subject.language>
  <subject.language>Ancient Sumerian</subject.language>
  <publisher>Oxford University Press</publisher>
  <publisher>http://www.oup.com/</publisher>
  <relation refine="requires">oai:sil:software/ipafont</relation>
  <relation refine="hasPart">oai:somearchive:holding126</relation>
  <relation refine="hasPart">oai:somearchive:holding127</relation>
  <relation refine="hasPart">oai:somearchive:holding128</relation>
  <relation refine="hasPart">oai:somearchive:holding129</relation>
  <relation refine="hasPart">oai:somearchive:holding130</relation>
  <relation refine="isPartOf">In Joel Sherzer and Greg Urban (eds.),
    Native South American discourse , 237-306. Berlin: Mouton.
  </relation>
  <source>oai:somearchive:holding1023</source>
  <source>Kwara'ae flora vocabulary extracted from Guide to the
    Forests of the British Solomon Islands, by T. C. Whitmore.
    Oxford University Press, 1966.</source>
  <subject scheme="LCSH">African languages</subject>
  <title>A Dictionary of the Nggela Language</title>
  <title lang="x-sil-LLU">Na tala 'uria na idulaa diana</title>
  <title refine="alternative" lang="en">The road to good reading</title>
  <type code="Image"/>
  <type.linguistic code="description/grammar"/>
  <type.linguistic code="transcription/orthographic"/>
</olac>
